export const ideasData = [
`Build a site with random photos of corgis on it (e.g. pulled automatically from <a href="https://unsplash.com/">Unsplash</a>)`,
`Create some type of lorem ipsum generator (e.g. with music terms)`,
`Generate automatic playlists using the <a href="https://musicbrainz.org/doc/MusicBrainz_API">MusicBrainz API</a>`,
`Generative art like the stuff from <a href="https://georgefrancis.dev/">George Francis</a>`,
`A collection of gifs/webps that do something cool together`,
`Single page site with something like 'd-e-f-i-n-t-l-y.com' (maybe acronym vs abbreviation)`,
`Color samples from movies showing tone of frames (e.g. get the main color from every frame and output them in an image where each pixel is represented by the color of the frame)`,
`Pull all frames from a movie and make them small thumbnails`,
`Pull thumbnails from frames of a movie and display them individually at random points of the page instead of showing them as a video. `,
`One of those things where you make a picture out of smaller images using movie thumbnails`,
`Some type of random generators (random color for example, maybe a random bar graph)`,
`Make some data visualizations with D3 `,
`A spinning photo of some type (like rotate it with some type of css of js, maybe multiple ones on the page?)`,
`Something with the konami code where it shows three characters to start and when you type it in it goes to 30.`,
`Whack-A-Mole`,
`Make a site with a sound board for clips from speek-and-spell`,
`One of those games with the paper thing with four pyramids that you put your fingers in and write letters and numbers on them and then close and open them and then lift a flap to see whatever's written there. `,
`Pick a random character and fill the window with it in a random order (this is one of the first things I did on my grandfather's TI-99/4A)`,
`Space Invaders clone`,
`Tic-tac-toe`,
`A "this page intentionally left blank" site with random fonts, colors, etc...`,
`Display a clock but instead of time show a corresponding ksuid`,
`A collection of javascript tools for text formatting (e.g. alphabetize a list, convert an unordered list to an ordered on and vice verse)`,
`Font book that shows fonts (pulls them automatically form google fonts as a dynamic load)`,
`Color pallet examples for frameworks like tailwind`,
`3d example of the default colors in a terminal (3js?)`,
`Some type of weather conditions/forecast site`,
`Random tik toc from favorites list`,
`Display a random quote from collection`,
`Stats on twitter followers (e.g. graph the number of followers each person who follows you has)`,
`Make a pong clone`,
`Make a tetris clone`,
`Make a battleship clone`,
`Make a minesweeper clone`,
`Make a space invaders clone`,
`Make a shoots and ladders clones`,
`Make a clone of basically any game out there`,
`Plot word frequencies for podcasts based on their transcripts`,
`Build a website with only a single html file with the words Hello, World in it`,
`Word stats from pages/sites that have RSS feeds (to make it easier to get the data)`,
`Stats on metadata from your photos (e.g what month do you take the most photos in)`,
`A bubble pop site like: https://bubblespop.netlify.app/`,
`A coin flip page`,
`A set of example data for different things (states, movies and directors and actors)h in different formats (csv, json, etc...)`,
`All work and no play makes jack a dull boy site (like https://jacktorrance.blog/) but set to music `,
`Matrix style green text animated page but you can change the color and the direction the glyphs move`,
`One of those matching faces games where there's a grid of tiles turned over an you pick two to try to match them, but use animated gifs`,
`Count-down timer to the next time your team plays (e.g. alabama football's next kick-off)`,
`"is YOUR TEAM playing today?" page with simple yes/no`,
`Something like: http://www.hasthelargehadroncolliderdestroyedtheworldyet.com/ that never changes`,
`Something with census data (e.g. make graphs of age distribution per state in D3)`,
`Graph of the number of national championships across different football teams and coaches`,
`Is it Friday yet single page site with yes/no. Could do something with time zones, (e.g it's 'mostly' friday if most timezones are in the day and 'barely, but not for you' when your timezone isn't but the international date line hasn't been hit)`,
`Days left in the year`,
`Days until various dates (holidays and vacations)`,
`Do something with remotion: https://www.remotion.dev/ `,
`Sound board with some random sounds`,
`Make a drum machine`,
`Single site page with a single gif on it`,
`Something like http://corndog.io/`,
`Random name generator (pulled from list of most popular names from different)`,
`Schedule and scores for your favorite sports team (e.g. alabama)`,
`Helmet/Hat schedule for a sports conference (e.g. https://fbschedules.com/2021-sec-football-helmet-schedule/)`,
`A page that shows tweets a select group of people in chronological order`,
`A page the embeds a youtube video multiple times but offsets their start by a little and only plays the audio from one `,
`A markov chain generator with terms from programming`,
`A markov chain generator with terms from football`,
`A page where you type in a sentence and it replaces certain words with related emoji`,
`The evil monkey image where it points to your cursor when you move it around`,
`Cheatsheets for things you constantly have to look up`,
`Make a new lens for snapchat and snapcam https://lensstudio.snapchat.com/`,
`Stock market it "is it up or is it down" app`,
`Show the sun's position in the sky throughout the day`,
`Sun rise and sunset times for the day`,
`Display the phase of the moon`,
`Show the percentage of the world that it's in today and tomorrow (or yesterday) based off time zones`,
`A place holder image site like https://placekitten.com/ but with giraffes`,
`A place holder image site like https://placekitten.com/ but with corgis`,
`Plot the weekly position over time of every song that hits the top ten`,
`An "All work and no play makes jack a dull boy" style page like https://jacktorrance.blog/`,
`A site that takes a list of twitch streamers and just auto plays one of the ones who's live`,
`Take math formulas and graph them`,
`Guess a number game with a random number where it says "You Win" if you get it and "You Lose" if you don't`,
`A twitter bot that posts a random image `,
`Personal resume site`,
`List of birthdays for the current date pulled from wikipedia`,
`Digital fireplace using javascript to create the flames with svgs`,
`Digital fishtank with javascript controlling the fish`,
`Personal github stats display with binary did I code today calendar`,
`Calendar that puts Xs over the days that have occurred`,
`Personal RSS feed reader`,
`Cylon with the red eye thing controlled by javascript/css`,
`Assemble a robot where you pick form a set of different arms/legs/bodies/heads to create a picture of a robot`,
`Personal movie review site with up/down ratings and stats of things like your favorite genre from https://www.themoviedb.org API`,
`Personal movie recommendation engine `,
`Display of which heroes were in which marvel movies`,
`Single page site to display a random thing from a set of things (e.g. a random idea from a set of ideas)`,
`Books I Have Read and What To Read list`,
`Personal calendar showing holidays you get off`,
`Twitter bot that watches for the word "pirate" then responds with "Arrrgh!"`,
`Do something like https://www.fugitivesheets.com/`,
`Personal page of bookmarks`,
`Personal page where you take forms from other sites and put them all in one place for easy access`,
`JavaScript tool to sort a list of text`,
`Math forms for things like figuring out what percentage one number is of another`,
`Make color pallets from your favorite games like: https://www.monumentpalettes.style/`,
`Automatic, random favicon generator that makes the different sizes of favicons for a site`,
`A clock page with clocks from different times zones`,
`Baseball cards with live stats`,
`A golf putting game`,
`A golf driving game`,
`A darts game`,
`A darts game, but with gravity reversed`,
`A pool/billiards game`,
`Model train style graphics you can assemble yourself`,
`A magic 8-ball`,
`Single serving site with description of a random Wikipedia page on each refresh`,
`Turn photos into 8-bit images`,
`Turn photos into 2-bit images`,
`A bot to find pages on StackOverflow with code samples that don't include proper "import", etc... calls`,
`A site the displays random programming snippets and explications on each refresh`,
`Build a chat app using web sockets`,
`Click/tap game where a target shows up randomly on the page that you have to cick and then another shows up and you're timed to see how quickly you can hit 20 of them`,
`Make a sudoku, but with emoji`,
`Make a sudoku game`,
`A red light, green light game where you have to click to make progress, but if you click when it's a red light you lose`,
`An automated screenshot re-namer that changes mac screenshot file names to something that actually sorts`,
`Make your own grimoire`,
`Build characters in CSS <a href="https://codepen.io/Niloofar_araz/pen/zYEpbKw">like these</a>`,
`Make your own programming challenge game like [Advent Of Code](https://adventofcode.com/)`,
`Write a blog post where you solve every day of [Advent Of Code](https://adventofcode.com/)`,
`Build a website/page as a subdomain of main site every day for 30 days (don't worry about quality, just get something posted)`,
`Use image recognition to count the number of chocolate chips in photos of cookies`,
`Do a data visualization showing the differences between ingredients of different types of coke/soda/pop`,
`Track your commute and run stats about which day averages the longest/shortest time `,
`Hamster Dance but with corgis`,
`Make a data viz with the <a href="https://citymapper.com/powers">City Mapper API</a>`,
`A Twitter bot that posts a photo of a random corgi photo from <a href="https://unsplash.com/">Unsplash</a> every few hours`,
`Build your own version of <a href="https://apod.nasa.gov/apod/astropix.html">Astronomy Picture Of the Day</a> from the <a href="https://data.nasa.gov/Space-Science/Astronomy-Picture-of-the-Day-API/ez2w-t8ua">NASA API</a>`,
`Make a space weather conditions site with data from the <a href="https://ccmc.gsfc.nasa.gov/donki/">Space Weather Database Of Notifications, Knowledge, Information (DONKI)</a> from <a href="https://ccmc.gsfc.nasa.gov/support/DONKI-webservices.php">NASA's API</a>`,
]