export const ideasData = [
`Build a site that displays a random photo of a corgis pulled automatically from <a href="https://unsplash.com/">Unsplash</a> every time you refresh the page`,
`Create some type of lorem ipsum generator (e.g. with music terms)`,
`Generate automatic playlists using the <a href="https://musicbrainz.org/doc/MusicBrainz_API">MusicBrainz API</a>`,
`Create generative art like the stuff from <a href="https://georgefrancis.dev/">George Francis</a>`,
`Make a collection of animated gifs/webps that do something cool together`,
`Use a word you have trouble remembering how to spell and make a site like <a href="https://d-e-f-i-n-i-t-e-l-y.com/">d-e-f-i-n-i-t-e-l-y.com</a>`,
`Extract and display color samples from movies showing the average color of each frame`,
`Pull all frames from a movie and make them small thumbnails and output them linerally`,
`Pull thumbnails from frames of a movie and display them individually at random points of the page instead of showing them as a video.`,
`Use the thumbnails of frames from a movie to create a timeline that shows only the first frame from each scene change `,
`Do one of those photo mosaic images where you make a picture out of smaller images using movie thumbnails (like <a href="https://www.pinterest.com/pin/692358142710574224/">this one</a>) but have the thumbnails transition between movies (e.g. Matrix 1, 2, 3, and 4)`,
`Setup a random color generator that shows complimentary colors as well`,
`Generate random color pallets based off color theory`,
`Spin multiple versions of a photo at different rates on one page (like rotate it with some type of css or js)`,
`Create a page that shows three copies of a character image that jumps to thirty if you enter the <a href="https://en.wikipedia.org/wiki/Konami_Code">konami code</a>`,
`Whack-A-Mole`,
`Make a site with a sound board of clips from <a href="https://www.youtube.com/watch?v=GBmg7WTyfYw">Speak and Spell/Math</a>`,
`Make your own synth voice like <a href="https://www.youtube.com/watch?v=GBmg7WTyfYw">Speak and Math</a>`,
`Make a web version of <a href="https://en.wikipedia.org/wiki/Speak_%26_Spell_(toy)">Speak and Spell</a>`,
`Make one of those games with the paper thing with four pyramids that you put your fingers in and write letters and numbers on them and then close and open them and then lift a flap to see whatever's written there`,
`Pick a random character and fill the window with it in a random order (this is one of the first things I did on my grandfather's TI-99/4A)`,
`Make a <a href="https://en.wikipedia.org/wiki/Space_Invaders">Space Invaders</a> clone`,
`Build a Tic-tac-toe game where you play against the computer`,
`A "this page intentionally left blank" site with random fonts, colors, etc...`,
`Make a clock but use <a href="https://github.com/segmentio/ksuid">KSUIDs</a> to display the time`,
`Make a <a href="https://en.wikipedia.org/wiki/Seven-segment_display">seven-segment display</a> clock`,
`Setup an "Is it Friday?" page with just a Yes/No answer on it`,
`Write a little tool to alphabetize lists of text`,
`Make a font book that shows font examples from google fonts but with a selection of colors and effects`,
`Make a font display page that lets you see multiple google fonts at the same time (e.g. as a heading and as body text)`,
`Make a <a href="https://en.wikipedia.org/wiki/Binary_clock">binary clock</a>`,
`Display color pallet examples for a CSS framework like <a href="https://tailwindcss.com/">tailwind</a>`,
`Plot default terminal colors in a 3D space with <a href="https://threejs.org/">three.js</a>`,
`Create a current weather conditions site`,
`Make a weather forecast page `,
`Setup a service that reads the weather forcast and lets you know if you should bring a coat or not`,
`Build a twitter bot to automatically post a random tik toc from a list of your favorites`,
`Make a page that displays a random quote from a collection you setup`,
`Run stats on twitter followers to see the distribution of the number of followers the folks who follow you have`,
`Make a <a href="https://en.wikipedia.org/wiki/Pong">pong</a> clone`,
`Make a jenga clone`,
`Make a tetris clone`,
`Make a battleship clone`,
`Make a minesweeper clone`,
`Make a space invaders clone`,
`Make a shoots/snakes and ladders clone`,
`Plot word frequencies for podcasts based on their transcripts`,
`Build a website with only a single html file (i.e. no framework) with the words &quot;Hello, World&quot;`,
`Get word stats from pages/sites that have RSS feeds (to make it easier to get the data)`,
`Build your own podcast feed with a collection of podcasts you like (e.g. <a href="https://www.alanwsmith.com/the-pod-of-alan">this one ;-)</a>) sorted in the order you like `,
`Run stats on the metadata for your photos to see what day of the week you take the most photos`,
`Make a bubble pop site like <a href="https://bubblespop.netlify.app/">this one</a>`,
`Setup a coin flip page`,
`Make an all work and no play makes jack a dull boy site (like <a href="https://jacktorrance.blog/">this</a>) but set to music `,
`Create a page with matrix style green text animated page but you can change the color and the direction the glyphs move`,
`Make one of those pair matching games where there's a grid of tiles that you turn over two at a time to find matches, but use animated gifs`,
`Setup a count-down timer showing how long until the next time your team plays`,
`Make an &quot;Is YOUR TEAM playing today?&quot; page with simple yes/no on it`,
`Pick a topic and make a site like <a href="http://www.hasthelargehadroncolliderdestroyedtheworldyet.com/">hasthelargehadroncolliderdestroyedtheworldyet</a> that never changes`,
`Create a data visualization in <a href="https://d3js.org/">D3</a> using census data to show the average age in each state`,
`Graph of the number of national championships across different football teams and coaches`,
`Build an &quot;Is it Friday yet&quot; single page site with yes/no. `,
`Setup a site that shows what percentage of the planet is in today/tomorrow/yesterday`,
`Make a count down page with the days left in the year`,
`Show a count down until all the various holidays you get off`,
`Do something with <a href="https://www.remotion.dev/">remotion</a>`,
`Make a sound board with random bird sounds sounds`,
`Make a drum machine`,
`Create a single page site with your favorite gif on it`,
`Create something like <a href="corndog.io/">corndog.io</a> but with corgis`,
`Make a random name generator (pulled from list of most popular names from different)`,
`Setup a display page to show the schedule and scores for your favorite team`,
`Build a Helmet/Hat schedule like <a href="https://fbschedules.com/2021-sec-football-helmet-schedule/">this one</a> that also shows scores and post-season play`,
`Setup a page that shows tweets from your favorite people in chronological order`,
`Make page the embeds a youtube video multiple times but offsets their start by a little and only plays the audio from one `,
`Build a <a href="https://en.wikipedia.org/wiki/Markov_chain">markov chain generator</a> with terms from programming`,
`Build a <a href="https://en.wikipedia.org/wiki/Markov_chain">markov chain generator</a> with terms from football`,
`Make a page where you type in a sentence and it replaces words with their related emoji`,
`Build an <a href="https://familyguy.fandom.com/wiki/Evil_Monkey">evil monkey</a> page where it points to your cursor when you move it around`,
`Setup cheatsheets for things you constantly have to look up`,
`Make a new lens for snapchat and snapcam with <a href="https://lensstudio.snapchat.com/">Lens Studio</a>`,
`Make a stock market it &quot;is it up or is it down&quot; app`,
`Build a display showing the sun&apos;s position in the sky throughout the day`,
`Setup a display sun rise and sunset times for the day`,
`Make a display showing the phase of the moon`,
`Build a place holder image site like <a href="https://placekitten.com/">Place Kitten</a> but with corgis`,
`Plot the weekly position over time of every song that hits the top ten`,
`Make a site that takes a list of twitch streamers and just auto plays one of the ones who's live randomly`,
`Display graphs of math formulas`,
`Make a <a href="https://play.battlesnake.com/">Battlesnake</a>`,
`Recreate <a href="https://www.youtube.com/watch?v=6WpMlwVwydo">Hampster Dance</a>`,
`Make a &quot;Guess the number&quot; game with a random number that says &quot;You Win&quot; if you get it and &quot;You Lose&quot; if you don't`,
`Setup a personal resume site`,
`Create a virtual <a href="https://en.wikipedia.org/wiki/Spirograph">spirograph</a>`,
`Setup a site that list people who's birthday is the current day with data from wikipedia`,
`Make a digital fireplace using javascript to create the flames with svgs`,
`Make a digital fishtank with javascript controlling the fish`,
`Pull your person github stats and display them on a calendar`,
`Make a calendar that puts an X over the days that have occurred`,
`Build a personal RSS feed reader`,
`Setup a Cylon image with the red eye sweep controlled by javascript/css`,
`Make a game where you assemble robots from different drawings of arms, legs, heads, and bodies. `,
`Setup a personal movie review site with up/down ratings and stats of things like your favorite genre from <a href="https://www.themoviedb.org">The Movie DB API</a>`,
`Generate a personal movie recommendation engine `,
`Create a data visualization which shows which heroes were in which marvel movies`,
`Make a personal &quot;Books I Have Read&quot; and &quot;Books I What To Read&quot; site`,
`Setup a personal calendar showing holidays you get off`,
`Make a twitter bot that watches for the word "pirate" then responds with "Arrrgh!"`,
`Do something like <a href="https://www.fugitivesheets.com/">Fugitive Sheets</a>`,
`Build a page to display a personal set of bookmarks and links`,
`Pull forms you use from other sites and put them on your own page`,
`Make a web page with a javascript tool that sorts lists alphabetically`,
`Create math forms for things like figuring out what percentage one number is of another`,
`Make color pallets from your favorite games like <a href="https://www.monumentpalettes.style/">Monument Pallets</a>`,
`Setup an automatic, random favicon generator that makes the different sizes of favicons for a site`,
`Create a clock page with clocks from different times zones`,
`Make baseball cards with live stats`,
`Make a golf putting game`,
`Make a golf driving game`,
`Make a darts game`,
`Make a darts game, but with gravity reversed`,
`Make a pool/billiards game`,
`Create a virtual model train project where you assemble graphics to make the track`,
`Make your own <a href="https://en.wikipedia.org/wiki/Magic_8-Ball">Magic 8-ball</a>`,
`Turn photos into 8-bit images`,
`Turn photos into 2-bit images`,
`Make a bot to find pages on StackOverflow with code samples that don't include proper "import", etc... calls (and then fix them)`,
`Build a site the displays random programming snippets and explications on each refresh`,
`Create a chat app using web sockets`,
`Create transcripts and closed caption automatically with the <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API">Web Speech API</a>`,
`Build a click/tap game where a target shows up randomly on the page that you have to cick and then another shows up and you're timed to see how quickly you can hit 20 of them`,
`Sudoku, but with emoji`,
`Make a sudoku game`,
`Create a red light, green light game where you have to click to make progress, but if you click when it's a red light you lose`,
`Build an automated screenshot re-namer that changes mac screenshot file names to something that actually sorts`,
`Make your own digital <a href="https://en.wikipedia.org/wiki/Grimoire">grimoire</a>`,
`Build characters in CSS <a href="https://codepen.io/Niloofar_araz/pen/zYEpbKw">like these</a>`,
`Make your own programming challenge game like <a href="https://adventofcode.com/">Advent Of Code</a>`,
`Write a blog post where you solve every day of <a href="https://adventofcode.com/">Advent Of Code</a>`,
`Build a single page website as a subdomain of your main site every day for 30 days (don't worry about quality, just get something posted)`,
`Use image recognition to count the number of chocolate chips in cookie photos`,
`Auto-generate <a href="https://en.wikipedia.org/wiki/Where%27s_Wally%3F">Where's Waldo</a> images`,
`Do a data visualization showing the differences between ingredients of different types of coke/soda/pop`,
`Track your commute and run stats about which day averages the longest/shortest time `,
`Make a data viz with the <a href="https://citymapper.com/powers">City Mapper API</a>`,
`Build a twitter bot that posts a photo of a random corgi photo from <a href="https://unsplash.com/">Unsplash</a> every day`,
`Build your own version of <a href="https://apod.nasa.gov/apod/astropix.html">Astronomy Picture Of the Day</a> from the <a href="https://data.nasa.gov/Space-Science/Astronomy-Picture-of-the-Day-API/ez2w-t8ua">NASA API</a>`,
`Build a <a href="https://en.wikipedia.org/wiki/Compound_interest">compound interest</a> calculator`,
`Make a space weather conditions site with data from the <a href="https://ccmc.gsfc.nasa.gov/donki/">Space Weather Database Of Notifications, Knowledge, Information (DONKI)</a> from <a href="https://ccmc.gsfc.nasa.gov/support/DONKI-webservices.php">NASA's API</a>`,
`Make a lorem ipsum generator with pirate talk`,
`Make a white noise generator with different choices for the audio track`,
`Visualize the sounds waveform of your favorite song`,
`Make Beat Saber as a typing game`,
`Plot the average beats per minute of top ten songs for the past fifty years`,
`Make word clouds for the number one songs of each year`,
`Make a D3 graph showing the number of times an artist made it to the top ten in the charts`,
`Plot the most frequent weekly downloads from npm`,
`Make a progress bar for the number of days in the year`,
`Make a video player that plays a random video from a curated playlist like <a href="https://www.surftech.tv/">surftech.tv</a> `,
`Show standard programming techniques (e.g. looping over a list/array) in seven different programming languages`,
`Build a personal version of a bookmark site like <a href="https://pinboard.in/">Pinboard</a>`,
`Setup a process to collect all the web pages you visit each day`,
`Make a <a href="https://en.wikipedia.org/wiki/Mastermind_(board_game)">Mastermind</a> clone`,
`Make Pokemon stat cards with the <a href="https://pokeapi.co/">PokeAPI</a>`,
`Make a text to brail tool`,
`Convert text to <a href="https://en.wikipedia.org/wiki/Morse_code">Morse code</a>`,
`Setup a graphic that shows the binary representations of letters you type`,
`Make word clouds from <a href="http://shakespeare.mit.edu/">Shakespeare</a>`,
]